"use client";

import { useState } from 'react';

export default function DocumentGenerator() {
  const [formData, setFormData] = useState({
    complainantName: '', incidentDate: '', policeStation: '', incidentDetails: ''
  });
  const [generatedDraft, setGeneratedDraft] = useState(null);

  const handleGenerate = () => {
    setGeneratedDraft(`
To,
The Station House Officer,
${formData.policeStation || '[Police Station Name]'},
[City, State]

Date: ${new Date().toLocaleDateString()}

Subject: First Information Report (FIR) regarding an incident on ${formData.incidentDate || '[Date]'}

Respected Sir/Madam,

I, ${formData.complainantName || '[Your Name]'}, residing at [Your Address], would like to bring to your attention the following incident:

${formData.incidentDetails || '[Description of the incident]'}

I request you to register an FIR and take immediate legal action in this matter under the applicable sections of the law.

Thanking you,
Yours sincerely,

___________________
(Signature)
${formData.complainantName || '[Your Name]'}
[Contact Number]
    `);
  };

  return (
    <div style={{ padding: '2rem 4rem', display: 'flex', gap: '2rem', minHeight: 'calc(100vh - 150px)', background: 'var(--bg-color)' }}>
      <div style={{ flex: 1, background: 'white', padding: '2rem', borderRadius: 'var(--border-radius-md)', boxShadow: 'var(--shadow-sm)' }}>
        <h1 style={{ fontSize: '1.8rem', marginBottom: '0.5rem', fontFamily: 'var(--font-playfair)' }}>Generate FIR Draft</h1>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem', fontSize: '0.9rem' }}>Fill out the details below to generate a standard police complaint template.</p>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <div>
            <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}>Complainant Name</label>
            <input type="text" value={formData.complainantName} onChange={e => setFormData({...formData, complainantName: e.target.value})} style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--border-radius-sm)', border: '1px solid #CCC', fontFamily: 'var(--font-inter)' }} />
          </div>
          <div>
            <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}>Target Police Station</label>
            <input type="text" value={formData.policeStation} onChange={e => setFormData({...formData, policeStation: e.target.value})} style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--border-radius-sm)', border: '1px solid #CCC', fontFamily: 'var(--font-inter)' }} />
          </div>
          <div>
            <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}>Date of Incident</label>
            <input type="date" value={formData.incidentDate} onChange={e => setFormData({...formData, incidentDate: e.target.value})} style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--border-radius-sm)', border: '1px solid #CCC', fontFamily: 'var(--font-inter)' }} />
          </div>
          <div>
            <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}>Incident Details</label>
            <textarea rows="5" value={formData.incidentDetails} onChange={e => setFormData({...formData, incidentDetails: e.target.value})} style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--border-radius-sm)', border: '1px solid #CCC', resize: 'vertical', fontFamily: 'var(--font-inter)' }}></textarea>
          </div>
          <button className="btn-primary" onClick={handleGenerate}>Generate Preview</button>
        </div>
      </div>

      <div style={{ flex: 1, background: '#F8F9FA', padding: '2rem', borderRadius: 'var(--border-radius-md)', border: '1px solid #EAEAEA', display: 'flex', flexDirection: 'column' }}>
        <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', fontFamily: 'var(--font-playfair)' }}>Document Preview</h2>
        {generatedDraft ? (
          <>
            <pre style={{ background: 'white', padding: '2rem', borderRadius: 'var(--border-radius-sm)', whiteSpace: 'pre-wrap', fontFamily: 'var(--font-inter)', fontSize: '0.9rem', lineHeight: 1.6, flex: 1, overflowY: 'auto', border: '1px solid #CCC' }}>
              {generatedDraft}
            </pre>
            <div style={{ marginTop: '1rem', fontSize: '0.8rem', color: 'var(--warning-color)', background: '#FFF3F3', padding: '1rem', borderRadius: '4px', border: '1px solid #FADBD8' }}>
              <strong>Disclaimer:</strong> Draft generated by Lex India for reference only. Review with a licensed advocate before formal submission.
            </div>
            <button className="btn-secondary" style={{ marginTop: '1rem', width: '100%' }}>Download as PDF</button>
          </>
        ) : (
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-secondary)' }}>
            Fill the form and generate to see the preview here.
          </div>
        )}
      </div>
    </div>
  );
}
